#!/bin/bash
node=$1
post=$2

if [ "${node}" = "stop" ]; then
	killall jackd
	sh cmdseq.sh stop
	exit $?
fi

if [ -z "${post}" ]; then
	if [ -z "${node}" ]; then
   		node=cod.gumb.private
	fi

	if ! jack_load netmanager; then
	    exit 1
        fi

	sleep 5
fi
sh cmdseq.sh start

##jack_disconnect ${node}:from_slave_1 system:playback_1
##jack_disconnect ${node}:from_slave_2 system:playback_2
#jack_connect ${node}:from_slave_1 system:playback_1
#jack_connect ${node}:from_slave_2 system:playback_1
#jack_connect ${node}:from_slave_2 system:playback_2
##jack_connect system:capture_1 ${node}:to_slave_1
#jack_connect system:capture_2 ${node}:to_slave_2
