#!/bin/bash

#ssh root@tang "sync; sync"

echo -n "shutdown pc y/n? "
read -n1 shutdownpc

echo
echo -n "continue y/n? "
read -n1 yn
echo

if [ "${yn}" != "y" ]; then
exit 0
fi

if [ -z "$1" ]; then
sh /home/john/sys x
fi

machines="$(cat machines)"

killall sdr-core

sh audiogo stop

for mc in ${machines}; do
	if ping -c1 -w1 ${mc} > /dev/null; then
                echo "powering off ${mc}...."
		ssh root@${mc} "poweroff &"
        else
                echo "powering off ${mc}....unreachable"
        fi
done
sleep 3

if [ "${shutdownpc}" = "y" ]; then
    sudo poweroff
fi
