#!/bin/bash

#ssh root@tang "sync; sync"
echo "confirm y/n"
read yn

if [ "${yn}" != "y" ]; then
exit 0
fi

if [ -z "$1" ]; then
sh /home/john/sys x
fi

machines="$(cat machines)"

killall sdr-core

sh audiogo stop

for mc in ${machines}; do
	if ping -c1 -w1 ${mc} > /dev/null; then
                echo "powering off ${mc}...."
		ssh root@${mc} "poweroff &"
        else
                echo "powering off ${mc}....unreachable"
        fi
done
sudo poweroff
